CREATE TABLE IF NOT EXISTS `Shazam-Artists` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `query_name` VARCHAR(100) NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE(`query_name`)
)